// do return some text widget
import 'package:flutter/material.dart';

import 'package:flutter_concepts/answer_button.dart';
import 'package:flutter_concepts/data/questions.dart';

class QuestionScreen extends StatefulWidget {
  const QuestionScreen({super.key});
  @override
  State<QuestionScreen> createState() {
    return _QuestionScreenState();
  }
}

class _QuestionScreenState extends State<QuestionScreen> {
  var currentQuestionIndex = 0; //why not use int instead?
  void answerQuestion() {
    setState(() {
      currentQuestionIndex++;
    });
  }

  @override
  Widget build(context) {
    final currentQuestion = questions[currentQuestionIndex];
    return SizedBox(
      width: double.infinity,
      child: Container(
        margin: const EdgeInsets.all(40),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center, //for vertical axis
          crossAxisAlignment: CrossAxisAlignment.stretch, //for horizontal axis
          children: [
            Text(
              currentQuestion.text,
              style: const TextStyle(
                color: Colors.white,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 30),
            //convert list of string to list of widget by using map() which allow to transform a value in a list to other value
            ...currentQuestion.getSuffledAnswer().map((answerItem) {
              return AnswerButton(
                  answerText: answerItem, onTap: answerQuestion);
            })
            /*... will added it as separate button in ,
            since children just want widgets as values inside this list, but we create a nested list inside a children widget list
            by using ... will pull each value out, of the iteratable, we spread list or iterable which is generated by map(), into a couple of individual values. 
            */
          ],
        ),
      ),
    );
  }
}
